# Generated by Django 4.2.3 on 2023-08-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mikrotik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("ip", models.IntegerField()),
                ("puertoweb", models.IntegerField()),
                ("puertoapi", models.IntegerField()),
                ("puertowinbox", models.IntegerField()),
                ("interfazWan", models.CharField(blank=True, max_length=50, null=True)),
                ("interfazlan", models.CharField(blank=True, max_length=50, null=True)),
                ("usuario", models.CharField(max_length=60)),
                ("contraseña", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Segmentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segmento", models.CharField(max_length=18)),
                (
                    "mikro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mikrotik.mikrotik",
                    ),
                ),
            ],
        ),
    ]
