# Generated by Django 4.2.3 on 2023-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mikrotik",
            name="ip",
            field=models.CharField(max_length=50),
        ),
    ]
