# Generated by Django 4.2.3 on 2023-08-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("mikrotik", "0002_alter_mikrotik_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=12)),
                ("subida", models.CharField(max_length=3)),
                ("bajada", models.CharField(max_length=3)),
                (
                    "cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "mikro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mikrotik.mikrotik",
                    ),
                ),
            ],
        ),
    ]
