# Generated by Django 4.2.5 on 2023-09-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "mikrotik",
            "0002_alter_grupocorte_acortar_alter_grupocorte_afacturar_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicio",
            name="max_limit",
        ),
        migrations.AddField(
            model_name="servicio",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mikrotik.planvelocidad",
            ),
            preserve_default=False,
        ),
    ]
