# Generated by Django 4.2.3 on 2023-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0003_servicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicio",
            name="bajada",
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="subida",
        ),
        migrations.AddField(
            model_name="servicio",
            name="max_limit",
            field=models.CharField(default="no hay nombre", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicio",
            name="nombre",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
