# Generated by Django 4.2.5 on 2023-09-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotik", "0007_grupocorte_hora"),
    ]

    operations = [
        migrations.CreateModel(
            name="planVelocidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.IntegerField()),
                ("velociadad", models.CharField(max_length=9)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("R", "Residencial"), ("C", "Corporativo")],
                        default="R",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="grupocorte",
            name="hora",
            field=models.TimeField(default="12:00am"),
        ),
    ]
