# Generated by Django 4.2.5 on 2023-09-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipodocu",
                    models.CharField(
                        choices=[
                            ("CC", "Cedula de ciudadania"),
                            ("NIT", "Numero de identificacion tributaria"),
                            ("PP", "Pasaporte"),
                            ("DIE", "Documento de identificacion extranjero"),
                            ("TE", "Tarjeta de extranjeria"),
                            ("R", "Residencial"),
                            ("C", "Corporativo"),
                        ],
                        default="CC",
                        max_length=3,
                    ),
                ),
                ("documento", models.CharField(max_length=50)),
                ("pais", models.CharField(max_length=50)),
                ("departamento", models.CharField(max_length=50)),
                ("municipio", models.CharField(max_length=50)),
                ("codigopostal", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
                ("corregimiento", models.CharField(max_length=50)),
                ("barrio", models.CharField(max_length=50)),
                ("correoelectronico", models.EmailField(max_length=254)),
                ("telefoo", models.CharField(max_length=50)),
                ("celular", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
    ]
