# Generated by Django 4.2.5 on 2023-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="cedula",
        ),
        migrations.AddField(
            model_name="cliente",
            name="barrio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="celular",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="codigopostal",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="corregimiento",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="correoelectronico",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="cliente",
            name="departamento",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="documento",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="municipio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pais",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefoo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipodocu",
            field=models.CharField(
                choices=[
                    ("CC", "Cedula de ciudadania"),
                    ("NIT", "Numero de identificacion tributaria"),
                    ("PP", "Pasaporte"),
                    ("DIE", "Documento de identificacion extranjero"),
                    ("TE", "Tarjeta de extranjeria"),
                    ("R", "Residencial"),
                    ("C", "Corporativo"),
                ],
                default="CC",
                max_length=3,
            ),
        ),
    ]
