# Generated by Django 4.2.5 on 2023-09-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="barrio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigopostal",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="corregimiento",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="departamento",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="municipio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pais",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
